version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-website
hooks:
   ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
   Install:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
   AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root

